# Material
- "." (period) / "dot" = dot product

## 14.2 What is a Matrix Decomposition
- Decomp = Decomposition

## 14.3 LU Decomposition
## 14.4 QR Decomposition
## 14.5 Cholesky Decomposition

In [1]:
import numpy as np
import scipy as sp
from scipy.linalg import lu

## 14.2 What is a Matrix Decomposition
1. Reducing a Matrix into its constituent parts
    1. Original : 10
    2. Decomp : 2 * 5
2. Also called Matrix factorization
3. More methods than what's below. See [Wiki](https://en.wikipedia.org/wiki/Matrix_decomposition)

## 14.3 LU Decomposition
1. For square Matrices
2. Decomp into L & U components
3. Notation : A = L . U <==> A = LU
    1. Decomp : A
    2. Lower Tria Matrix : L
    2. Upper Tria Matrix : U
4. Can fail so to aid this use LUP
    1. LUP : LU (as above)
    2. P : decomp w/ partial pivoting; a Matrix; returns result to originial order after re-ordering the rows of the parent Matrix
    3. A = L . U . P
5. Other methods to a support LU Decomp
6. Often used to calc/simplify sys of lin eqs sa :
    1. Finding the coefficients in lin regression
    2. Calc the determinant
    3. Calc the inverse

In [8]:
# 3 x 3 square Matrix
D = np.array([
             [1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]
             ])
print("D.shape : ", D.shape, "\nD : \n", D)

print("\n#### FACTOR - DECMOP ####")

P, L, U = sp.linalg.lu(D)
print("\n>> P.shape : ", P.shape, "\n>> P : \n", P, 
      "\n\n>> L.shape : ", L.shape, "\n>> L : \n", L, 
     "\n\n>> U.shape : ", U.shape, "\n>> U : \n", U
     )

print("\n#### RECONSTRUCT ####")
P_dot_L_dot_U = P.dot(L).dot(U)
print("\n>> P_dot_L_dot_U.shape : ", P_dot_L_dot_U.shape, "\n>> P_dot_L_dot_U : \n", P_dot_L_dot_U)

# another way to write J
my_dot = np.dot(np.dot(P, L), U)
print("\n>> my_dot.shape : ", my_dot.shape, "\n>> my_dot : \n", my_dot)

D.shape :  (3, 3) 
D : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

#### FACTOR - DECMOP ####

>> P.shape :  (3, 3) 
>> P : 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 

>> L.shape :  (3, 3) 
>> L : 
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]] 

>> U.shape :  (3, 3) 
>> U : 
 [[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]

#### RECONSTRUCT ####

>> P_dot_L_dot_U.shape :  (3, 3) 
>> P_dot_L_dot_U : 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

>> my_dot.shape :  (3, 3) 
>> my_dot : 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 14.4 QR Decomposition
1. For e x a Matrices (! limited to square Matrices)
2. Notation : A = Q . R <==> A = QR
    1. Q : size e x e
    2. R : size e x a (upper tria Matrix)
3. Can fail
4. Used to solve sys of lin eqs
5. Returns Q & R Matrices w/ smaller or reduced dims
    1. More economical/ efficient

In [9]:
# 3 x 2 square Matrix
D = np.array([
             [1, 2],
             [3, 4],
             [5, 6]
             ])
print("D.shape : ", D.shape, "\nD : \n", D)

print("\n#### FACTOR - DECMOP ####")

# complete : ! required but used to return Q & R to expected sizes
Q, R = np.linalg.qr(D, 'complete')
print("\n>> Q.shape : ", Q.shape, "\n>> Q : \n", Q, 
      "\n\n>> R.shape : ", R.shape, "\n>> R : \n", R, 
     )

print("\n#### RECONSTRUCT ####")
J = np.dot(Q, R)
print("\n>> J.shape : ", J.shape, "\n>> J : \n", J)

D.shape :  (3, 2) 
D : 
 [[1 2]
 [3 4]
 [5 6]]

#### FACTOR - DECMOP ####

>> Q.shape :  (3, 3) 
>> Q : 
 [[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]] 

>> R.shape :  (3, 2) 
>> R : 
 [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]

#### RECONSTRUCT ####

>> J.shape :  (3, 2) 
>> J : 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


## 14.5 Cholesky Decomposition
- Cholesky : co-lesk-kee
1. For square symmetric Matrices
2. (+) definite Matrix : All entries > 0
3. Notation : A = L . L^T <==> A = LL^T <==> A = U^T . U <==> A = U^TU
    1. Decomp : Matrix A
    2. Lower tria Matrix : L
    3. Lower tria Matrix transpose : L^T
    4. Upper tria Matrix transpose : U^T
    5. Upper tria Matrix : U
4. Used to solve
    1. Lin least squares for lin regression
    2. Simulation & optimization methods
5. Nearly 2x efficient as the LU decomp when performing on symmetical Matrices
6. Returns L 

In [ ]:
# 3 x 3 square Matrix
D = np.array([
             [2, 1, 1],
             [1, 2, 1],
             [1, 1, 2]
             ])
print("D.shape : ", D.shape, "\nD : \n", D)

print("\n#### FACTOR - DECMOP ####")

L = np.linalg.cholesky(D)
print("\nL.shape : ", L.shape, "\nL : \n", L)

L_T = np.transpose(L)
print("\nL_T.shape : ", L_T.shape, "\nL_T : \n", L_T)

print("\n#### RECONSTRUCT ####")
J = np.dot(L, L_T)
print("J.shape : ", J.shape, "\nJ : \n", J)
