# Material

## 14.2 What is a Matrix Decomposition
- Decomp = Decomposition

## 14.3 LU Decomposition
## 14.4 QR Decomposition
## 14.5 Cholesky Decomposition

In [1]:
import numpy as np
import scipy as sp
from scipy.linalg import lu

## 14.2 What is a Matrix Decomposition

- Also called Matrix factorization bc it's thought of to factor a #; ie 10 can be factored in 2 x 5
- More methods than what's below. See [Wiki](https://en.wikipedia.org/wiki/Matrix_decomposition)
***

### 1. What is MD?

1. Matrix Decomposition is reducing/factoring a Matrix into its constituent parts to make it easier to solve
 
2. <b> High-lvl importance (R3 & crew) : </b> Lego blocks (Lb) : Let's say that I build a barrier/wall w/ each wall being a diff color. Your goal is to decompose or sort this structure by the 4 colors bc it's time to clean up.

3. <b> Low-lvl importance (Grad student) : </b> Limitations of PCs w/ complex matrix operations result in inefficiency of the computation. 

4. <b> Additionally : </b> Think about Master of Change book : A $ \rightarrow $ B $ \rightarrow $ C, where 
    - A is the original Matrix, which is complex
    - B is the decomposition technique applied to A
    - C is the resulting Matrix, which is easier to interpret
***

### 2. Why is MD important?

1. <b> High-lvl importance (R3 & crew) : </b> Possible strategy to clean up is to breakdown wall by wall. Why? To simplify the complexity of breaking down all 4 walls/colors at once.

2. <b> Low-lvl importance (Grad student) : </b> To simplify the complex Matrix operation(s), $ \therefore $ increase the computation efficiency
***

### 3. What are some applications of MD? What other concepts can I connect to this? Use when...

1. Solving sys of linear eqs

2. Calc the inverse [see 11.3](https://github.com/Brinkley97/lin_alg_for_ml_jason_brownlee/blob/main/part_iv_matrices/11-matrix_operations/11.ipynb)

3. Calc the det(D) [see 11.5](https://github.com/Brinkley97/lin_alg_for_ml_jason_brownlee/blob/main/part_iv_matrices/11-matrix_operations/11.ipynb)

4. [Back propagation](https://arxiv.org/abs/2201.00145)
***

### 4. What is the evolution of MD? In np?

1. [Two Purposes for Matrix Factorization : A Historical Appraisal*](https://www.jstor.org/stable/2653377?seq=1#metadata_info_tab_contents)

2. [Matrix Decomposition and Applications](https://arxiv.org/abs/2201.00145)

3. [History and generality of the CS decomposition](https://www.sciencedirect.com/science/article/pii/0024379594904464)
* TO DO : Read resources along w/ more & type notes here
***

### 5. Can I predict the future use of MD? How can this current usage improve?

* TO DO : Learn more on this
***

### 6. What don't I understand? Why is this? What's the root of this misunderstanding?

## 14.3 LU Decomposition

### 1. Why use LUD?
1. Only for square Matrices

***

### 2. How to compute the LUD?
1. Notation : A = L $ \cdot $ U $ \iff $ A = LU
    1. Decomp : A
    2. Lower Tria Matrix : L
    3. Upper Tria Matrix : U
2. See process [here](https://github.com/Brinkley97/lin_alg_for_ml_jason_brownlee/blob/main/part_v_factorization/14-matrix_decomposition/luBreakdown.ipynb)
*** 

### 3. Application & concepts to connect
1. Finding the coefficients in lin regression

2. Calc the inverse [see 11.3](https://github.com/Brinkley97/lin_alg_for_ml_jason_brownlee/blob/main/part_iv_matrices/11-matrix_operations/11.ipynb)

3. Calc the det(D) [see 11.5](https://github.com/Brinkley97/lin_alg_for_ml_jason_brownlee/blob/main/part_iv_matrices/11-matrix_operations/11.ipynb)

*** 

### 4. Other
1. LU can fail for Matrices that can't be decomp at all & some that can't be decomp so easily <b> so to aid this use LUP </b> bc it's numerically more stable
    1. LUP : LU (as above)
    2. P : decomp w/ partial pivoting
        - re-ordering the rows of the parent Matrix (A) to simply the decomp process
        - returns result to originial order after 
    3. A = L $ \cdot $ U $ \cdot $ P $ \iff $ A = LUP

In [2]:
# 3 x 3 square Matrix
D = np.array([
             [1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]
             ])
print("D.shape : ", D.shape, "\nD : \n", D)

print("\n#### FACTOR - DECMOP ####")

P, L, U = sp.linalg.lu(D)
print("\n>> P.shape : ", P.shape, "\n>> P : \n", P, 
      "\n\n>> L.shape : ", L.shape, "\n>> L : \n", L, 
     "\n\n>> U.shape : ", U.shape, "\n>> U : \n", U
     )

print("\n#### RECONSTRUCT ####")
P_dot_L_dot_U = P.dot(L).dot(U)
print("\n>> P_dot_L_dot_U.shape : ", P_dot_L_dot_U.shape, "\n>> P_dot_L_dot_U : \n", P_dot_L_dot_U)

# another way to write J
my_dot = np.dot(np.dot(P, L), U)
print("\n>> my_dot.shape : ", my_dot.shape, "\n>> my_dot : \n", my_dot)

D.shape :  (3, 3) 
D : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

#### FACTOR - DECMOP ####

>> P.shape :  (3, 3) 
>> P : 
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 

>> L.shape :  (3, 3) 
>> L : 
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]] 

>> U.shape :  (3, 3) 
>> U : 
 [[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]

#### RECONSTRUCT ####

>> P_dot_L_dot_U.shape :  (3, 3) 
>> P_dot_L_dot_U : 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

>> my_dot.shape :  (3, 3) 
>> my_dot : 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 14.4 QR Decomposition


### 1. Why use QRD?
1. Bc it's ! limited to square Matrices
2. Bc it's $ \lnot $ (not) limited to square Matrices
3. Returns Q & R Matrices w/ smaller or reduced dims $ \implies $ more economical/efficient

***

### 2. How to compute the QRD?
1. Notation : A = Q $ \cdot $ R $ \iff $ A = QR
    1. e $ \times $ a (Decomp) : A
    2. a $ \times $ a : Q
    3. a $ \times $ e (Upper Tria Matrix) : R
2. See process [here](https://github.com/Brinkley97/lin_alg_for_ml_jason_brownlee/blob/main/part_v_factorization/14-matrix_decomposition/qrBreakdown.ipynb)

- TO DO : figure out why I'm getting
    1. w/ out the complete param, 
        1. e $ \times $  a : Q
        2. a $ \times $ a (Upper Tria Matrix) : R
    2. w/ the complete param,
        1. e $ \times $  e : Q
        2. e $ \times $ a (Upper Tria Matrix) : R
*** 

### 3. Application & concepts to connect
1. Solving sys of lin eqs

*** 

### 4. Other
1. QRD can fail for Matrices that can't be decomp at all & some that can't be decomp so easily

In [3]:
# 3 x 2 square Matrix
D = np.array([
             [1, 2],
             [3, 4],
             [5, 6]
             ])
print("D.shape : ", D.shape, "\nD : \n", D)

print("\n#### FACTOR - DECMOP w/ out the complete arg ####")

# complete : ! required but used to return Q & R to expected sizes
Q, R = np.linalg.qr(D)
print("\n>> Q.shape : ", Q.shape, "\n>> Q : \n", Q, 
      "\n\n>> R.shape : ", R.shape, "\n>> R : \n", R, 
     )

print("\n#### RECONSTRUCT ####")
Q_dot_R = np.dot(Q, R)
print("\n>> Q_dot_R.shape : ", Q_dot_R.shape, "\n>> Q_dot_R : \n", Q_dot_R)

print("\n")
print("\n#### FACTOR - DECMOP w/ the complete arg ####")

# complete : ! required but used to return Q & R to expected sizes
Q, R = np.linalg.qr(D, 'complete')
print("\n>> Q.shape : ", Q.shape, "\n>> Q : \n", Q, 
      "\n\n>> R.shape : ", R.shape, "\n>> R : \n", R, 
     )

print("\n#### RECONSTRUCT ####")
Q_dot_R = np.dot(Q, R)
print("\n>> Q_dot_R.shape : ", Q_dot_R.shape, "\n>> Q_dot_R : \n", Q_dot_R)

D.shape :  (3, 2) 
D : 
 [[1 2]
 [3 4]
 [5 6]]

#### FACTOR - DECMOP w/ out the complete arg ####

>> Q.shape :  (3, 2) 
>> Q : 
 [[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]] 

>> R.shape :  (2, 2) 
>> R : 
 [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]

#### RECONSTRUCT ####

>> Q_dot_R.shape :  (3, 2) 
>> Q_dot_R : 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]



#### FACTOR - DECMOP w/ the complete arg ####

>> Q.shape :  (3, 3) 
>> Q : 
 [[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]] 

>> R.shape :  (3, 2) 
>> R : 
 [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]

#### RECONSTRUCT ####

>> Q_dot_R.shape :  (3, 2) 
>> Q_dot_R : 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


## 14.5 Cholesky Decomposition
- Cholesky : co-lesk-kee

### 1. Why use CD?
1. For square symmetric Matrices where (+) definite Matrix $ \implies $ all entries > 0
2. Nearly 2x efficient as the LUD when performing on symmetical Matrices

***

### 2. How to compute the CD?
1. Notation : A = Q $ \cdot $ R $ \iff $ A = QR
    1. e $ \times $ a (Decomp) : A
    2. a $ \times $ a : Q
    3. a $ \times $ e (Upper Tria Matrix) : R

1. Notation : A = L $ \cdot $ L$ ^T $ $ \iff $ A = LL$ ^T $ $ \iff $ A = U$ ^T $ $ \cdot $ U $ \iff $ A = U$ ^T $ U
    1. Decomp : Matrix A
    2. Lower tria Matrix : L
    3. Lower tria Matrix transpose : L$ ^T $
    4. Upper tria Matrix transpose : U$ ^T $
    5. Upper tria Matrix : U
    6. Returns : L
2. See process [here](https://github.com/Brinkley97/lin_alg_for_ml_jason_brownlee/blob/main/part_v_factorization/14-matrix_decomposition/choleskyBreakdown.ipynb)

*** 

### 3. Application & concepts to connect
1. Solving lin least squares for lin regression
2. Calc simulation & optimization methods

In [4]:
# 3 x 3 square Matrix
D = np.array([
             [2, 1, 1],
             [1, 2, 1],
             [1, 1, 2]
             ])
print("D.shape : ", D.shape, "\nD : \n", D)

print("\n#### FACTOR - DECMOP ####")

L = np.linalg.cholesky(D)
print("\n>> L.shape : ", L.shape, "\n>> L : \n", L)

print("\n#### RECONSTRUCT ####")

L_T = np.transpose(L)
print("\n>> L_T.shape : ", L_T.shape, "\n>> L_T : \n", L_T)

L_dot_L_T = np.dot(L, L_T)
print("\n>> L_dot_L_T.shape : ", L_dot_L_T.shape, "\n>> L_dot_L_T : \n", L_dot_L_T)


D.shape :  (3, 3) 
D : 
 [[2 1 1]
 [1 2 1]
 [1 1 2]]

#### FACTOR - DECMOP ####

>> L.shape :  (3, 3) 
>> L : 
 [[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]

#### RECONSTRUCT ####

>> L_T.shape :  (3, 3) 
>> L_T : 
 [[1.41421356 0.70710678 0.70710678]
 [0.         1.22474487 0.40824829]
 [0.         0.         1.15470054]]

>> L_dot_L_T.shape :  (3, 3) 
>> L_dot_L_T : 
 [[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
