# Materials

## 11.2 Transpose
## 11.3 Inverse
## 11.4 Trace
## 11.5 Determinant 
## 11.6 Rank

In [1]:
import numpy as np

## 11.2 Transpose


In [2]:
# 3 x 2
D = np.array([
             [1, 2],
             [3, 4],
             [5, 6],
             ])
print("D : \n", D)

# transpose 1 
print("D.T : \n", D.T)

# transpose 2 
print("np.transpose(D) : \n", np.transpose(D))

D : 
 [[1 2]
 [3 4]
 [5 6]]
D.T : 
 [[1 3 5]
 [2 4 6]]
np.transpose(D) : 
 [[1 3 5]
 [2 4 6]]


## 11.3 Inverse

In [8]:
# 2 x 2
D = np.array([
             [1, 2],
             [3, 4],
             ])
print("D : \n", D)

D_inv = np.linalg.inv(D)
print("\nD_inv : \n", D_inv)

print("\nD dot D_inv = Identity : \n", np.dot(D, D_inv))

D : 
 [[1 2]
 [3 4]]

D_inv : 
 [[-2.   1. ]
 [ 1.5 -0.5]]

D dot D_inv = Identity : 
 [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


## 11.4 Trace

In [9]:
# 3 x 3
D = np.array([
             [1, 2, 3],
             [4, 5, 6],
             [7, 8, 9],
             ])
print("D : \n", D)

D_trace = np.trace(D)
print("\nD_trace : \n", D_trace)



D : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

D_trace : 
 15


## 11.5 Determinant

In [12]:
# 3 x 3
D = np.array([
             [1, 2, 3],
             [4, 5, 6],
             [7, 8, 9],
             ])
print("D : \n", D)

D_determinat = np.linalg.det(D)
print("\nD_determinant : \n", D_determinat)

D : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

D_determinant : 
 -9.51619735392994e-16


## 11.6 Rank

In [20]:
# 1 x 3 rank
d1 = np.array([1, 2, 3])
print("d1 : ", d1)

dr1 = np.linalg.matrix_rank(d1)
print("dr1 : ", dr1)

# 1 x 5 0 rank 
d2 = np.array([0, 0, 0, 0, 0])
print("\nd2 : ", d2)

dr2 = np.linalg.matrix_rank(d2)
print("dr2 : ", dr2)

# more ex
d3 = np.array([8, 0, 0, 0, 0])
print("\nd3 : ", d3)

dr3 = np.linalg.matrix_rank(d3)
print("dr3 : ", dr3)

## 5 x 1
d4 = np.array([
              [8], 
              [0], 
              [0], 
              [0], 
              [0]
              ])

print("\n4 : ", d4)

dr4 = np.linalg.matrix_rank(d4)
print("dr4 : ", dr4)


## 5 x 2
d5 = np.array([
              [8, 0], 
              [0, 0], 
              [0, 0], 
              [0, 0], 
              [0, 0]
              ])

print("\n5 : ", d5)

dr5 = np.linalg.matrix_rank(d5)
print("dr5 : ", dr5)

d1 :  [1 2 3]
dr1 :  1

d2 :  [0 0 0 0 0]
dr2 :  0

d3 :  [8 0 0 0 0]
dr3 :  1

4 :  [[8]
 [0]
 [0]
 [0]
 [0]]
dr4 :  1

5 :  [[8 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
dr5 :  1
